//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IntifaceGameHapticsRouter {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.8.1.0")]
    internal sealed partial class IntifaceGameHapticsRouterProperties : global::System.Configuration.ApplicationSettingsBase {
        
        private static IntifaceGameHapticsRouterProperties defaultInstance = ((IntifaceGameHapticsRouterProperties)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new IntifaceGameHapticsRouterProperties())));
        
        public static IntifaceGameHapticsRouterProperties Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ConnectOnStartup {
            get {
                return ((bool)(this["ConnectOnStartup"]));
            }
            set {
                this["ConnectOnStartup"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ws://127.0.0.1:12345")]
        public string WebsocketAddress {
            get {
                return ((string)(this["WebsocketAddress"]));
            }
            set {
                this["WebsocketAddress"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public double VibrationMultiplier {
            get {
                return ((double)(this["VibrationMultiplier"]));
            }
            set {
                this["VibrationMultiplier"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("200")]
        public int BluetoothTiming {
            get {
                return ((int)(this["BluetoothTiming"]));
            }
            set {
                this["BluetoothTiming"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool UseEmbedded {
            get {
                return ((bool)(this["UseEmbedded"]));
            }
            set {
                this["UseEmbedded"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool UseRemote {
            get {
                return ((bool)(this["UseRemote"]));
            }
            set {
                this["UseRemote"] = value;
            }
        }
    }
}
