name: GHR CI Build

on:
  push:
    branches:
      - dev
      - master
    tags:
      - 'v*'      
      
jobs:
  build-stable:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]
    steps:
    - uses: actions/checkout@v2
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.1
    - uses: nuget/setup-nuget@v1
    - run: nuget restore IntifaceGameHapticsRouter.sln      
    - name: Build app for release
      run: msbuild IntifaceGameHapticsRouter.sln -t:rebuild -property:Configuration=Release      
    - name: Build Innosetup Installer
      shell: pwsh
      env:
        BUILD_VERSION: ${{ github.ref_name }}
      run: |
        iscc .\intiface-ghr-installer.iss
    - name: Archive production artifacts
      uses: actions/upload-artifact@v4
      with:
        name: windows-installer
        path: |
          installer/intiface-game-haptics-router-installer.exe